### PR TITLE
setup-java v2

### PR DESCRIPTION
**Pull request by sullis**
https://github.com/actions/setup-java/blob/main/README.md

### CODE REVIEW

**Comment by fdw** [comment]
Hey, thank you! I think we rather want to use Adopt OpenJDK than Zulu. Can you please change that before we merge?

**Comment by sullis** [comment]
> Hey, thank you! I think we rather want to use Adopt OpenJDK than Zulu. Can you please change that before we merge?

Done.

**Comment by fdw** [comment]
Thank you!

**Review by fdw — APPROVED** [review]

**Comment by fdw** [comment]
As this isn't working, I'm closing it now.

**Pull request closed without merging**
